# Generated by Django 4.0.3 on 2022-04-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_roll_no_customuser_gender_remove_student_roll_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
