# Generated by Django 4.0.3 on 2022-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('Coaches', 'Coaches'), ('Owner', 'Owner')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
