# Generated by Django 4.0.3 on 2022-04-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customuser_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('otp_type', models.CharField(choices=[('FP', 'Forgot_Password'), ('UC', 'User_Creation'), ('CE', 'Chnge_Email')], default='UC', max_length=50)),
            ],
            options={
                'db_table': 'verify_otp',
            },
        ),
    ]
