# Generated by Django 4.0.3 on 2022-04-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyotp',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
