# Generated by Django 4.0.3 on 2022-04-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_verifyotp_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyotp',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
