# Generated by Django 4.0.3 on 2022-04-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_verifyotp_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifyotp',
            name='created_date',
        ),
    ]
