# Generated by Django 4.0.3 on 2022-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_delete_verifyotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('query_string', models.CharField(max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'verify_otp',
            },
        ),
    ]
