# Generated by Django 4.0.3 on 2022-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('coach', 'Coach'), ('owner', 'Owner')], default='owner', max_length=20),
        ),
    ]
