# Generated by Django 4.0.3 on 2022-03-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Owner_Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Sport_Center', models.CharField(max_length=100)),
                ('Contact_No', models.BigIntegerField()),
                ('Action', models.CharField(max_length=100)),
            ],
        ),
    ]
