# Generated by Django 4.0.3 on 2022-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Timings', models.TimeField()),
                ('Contact', models.BigIntegerField()),
                ('Action', models.CharField(max_length=100)),
            ],
        ),
    ]
