# Generated by Django 4.0.3 on 2022-03-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
                ('password2', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
