# Generated by Django 4.0.3 on 2022-03-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_account_delete_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports',
            name='Action',
        ),
        migrations.AlterField(
            model_name='sports',
            name='Timings',
            field=models.TimeField(blank=True, choices=[('00:00:00', 'Midnight'), ('01:00:00', '01 AM'), ('02:00:00', '02 AM'), ('03:00:00', '03 AM'), ('04:00:00', '04 AM'), ('05:00:00', '05 AM'), ('06:00:00', '06 AM'), ('07:00:00', '07 AM'), ('08:00:00', '08 AM'), ('09:00:00', '09 AM'), ('10:00:00', '10 AM'), ('11:00:00', '11 AM'), ('12:00:00', 'Noon'), ('13:00:00', '01 PM'), ('14:00:00', '02 PM'), ('15:00:00', '03 PM'), ('16:00:00', '04 PM'), ('17:00:00', '05 PM'), ('18:00:00', '06 PM'), ('19:00:00', '07 PM'), ('20:00:00', '08 PM'), ('21:00:00', '09 PM'), ('22:00:00', '10 PM'), ('23:00:00', '11 PM')], null=True),
        ),
    ]
