# Generated by Django 4.0.3 on 2022-03-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_sports_timings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('SportsCenter', models.CharField(max_length=100)),
                ('Contact', models.BigIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Sports',
            new_name='SportsCenter',
        ),
    ]
