# Generated by Django 4.0.3 on 2022-03-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_coaches_rename_sports_sportscenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('SportsCenter', models.CharField(max_length=70)),
                ('Sport', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('Coach', models.CharField(max_length=40)),
                ('SportsCenter', models.CharField(max_length=50)),
                ('Timings', models.TimeField(blank=True, choices=[('00:00:00', 'Midnight'), ('01:00:00', '01 AM'), ('02:00:00', '02 AM'), ('03:00:00', '03 AM'), ('04:00:00', '04 AM'), ('05:00:00', '05 AM'), ('06:00:00', '06 AM'), ('07:00:00', '07 AM'), ('08:00:00', '08 AM'), ('09:00:00', '09 AM'), ('10:00:00', '10 AM'), ('11:00:00', '11 AM'), ('12:00:00', 'Noon'), ('13:00:00', '01 PM'), ('14:00:00', '02 PM'), ('15:00:00', '03 PM'), ('16:00:00', '04 PM'), ('17:00:00', '05 PM'), ('18:00:00', '06 PM'), ('19:00:00', '07 PM'), ('20:00:00', '08 PM'), ('21:00:00', '09 PM'), ('22:00:00', '10 PM'), ('23:00:00', '11 PM')], null=True)),
                ('Package', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Transcations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=40)),
                ('Role', models.CharField(max_length=50)),
                ('SportsCenter', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
