# Generated by Django 4.0.3 on 2022-03-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_categories_schedule_transcations_delete_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SportsCenter', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=60)),
                ('Amount', models.BigIntegerField()),
                ('Duration', models.CharField(max_length=50)),
            ],
        ),
    ]
