# Generated by Django 4.0.3 on 2022-03-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_subscriptionplans'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsCenterOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=60)),
                ('SportsCenter', models.CharField(max_length=50)),
                ('Contact', models.BigIntegerField()),
            ],
        ),
    ]
