# Generated by Django 4.0.3 on 2022-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_sportscenterowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Timings',
            field=models.CharField(blank=True, choices=[('02:00:00', '05 AM'), ('05:00:00', '08 AM'), ('08:00:00', '11 AM'), ('11:00:00', '14 PM'), ('14:00:00', '17 PM'), ('17:00:00', '20 PM'), ('20:00:00', '23 PM'), ('23:00:00', '01 AM')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sportscenter',
            name='Timings',
            field=models.CharField(blank=True, choices=[('02:00:00', '05 AM'), ('05:00:00', '08 AM'), ('08:00:00', '11 AM'), ('11:00:00', '14 PM'), ('14:00:00', '17 PM'), ('17:00:00', '20 PM'), ('20:00:00', '23 PM'), ('23:00:00', '01 AM')], max_length=30, null=True),
        ),
    ]
