# Generated by Django 4.0.3 on 2022-03-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_schedule_timings_alter_sportscenter_timings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoachName', models.CharField(max_length=60)),
                ('Location', models.CharField(max_length=60)),
                ('SportsCenter', models.CharField(max_length=70)),
                ('Contact', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='Timings',
            field=models.CharField(blank=True, choices=[('02 AM', '05 AM'), ('05 AM', '08 AM'), ('08 AM', '11 AM'), ('11 AM', '02 PM'), ('02 PM', '05 PM'), ('05 PM', '08 PM'), ('08 PM', '11 PM'), ('11 PM', '01 AM')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sportscenter',
            name='Timings',
            field=models.CharField(blank=True, choices=[('02 AM', '05 AM'), ('05 AM', '08 AM'), ('08 AM', '11 AM'), ('11 AM', '02 PM'), ('02 PM', '05 PM'), ('05 PM', '08 PM'), ('08 PM', '11 PM'), ('11 PM', '01 AM')], max_length=30, null=True),
        ),
    ]
