# Generated by Django 4.0.3 on 2022-03-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_coachmanagement_alter_schedule_timings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedSportsCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('Location', models.CharField(max_length=50)),
                ('Owner', models.CharField(max_length=90)),
                ('Contact', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Location', models.CharField(max_length=60)),
                ('Email', models.EmailField(max_length=70)),
                ('Contact', models.BigIntegerField()),
            ],
        ),
    ]
