# Generated by Django 4.0.3 on 2022-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_rename_assignedsportscenter_assignedpendingsportscenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Timings',
            field=models.CharField(blank=True, choices=[('05 AM', '08 PM')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sportscenter',
            name='Timings',
            field=models.CharField(blank=True, choices=[('05 AM', '08 PM')], max_length=30, null=True),
        ),
    ]
