# Generated by Django 4.0.3 on 2022-03-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_schedule_timings_alter_sportscenter_timings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='Timings',
            field=models.CharField(blank=True, choices=[('05 AM', '6PM')], max_length=40, null=True),
        ),
    ]
