# Generated by Django 4.0.3 on 2022-03-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_schedule_timings_alter_sportscenter_timings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='password',
            new_name='ConfirmPassword',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='password2',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='UserName',
        ),
        migrations.AddField(
            model_name='account',
            name='Contact',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='Gender',
            field=models.CharField(default=None, max_length=70),
            preserve_default=False,
        ),
    ]
