# Generated by Django 4.0.3 on 2022-03-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_user_delete_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
