# Generated by Django 4.0.3 on 2022-03-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_rename_contact_assignedpendingsportscenter_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedpendingsportscenter',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='coaches',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='coachmanagement',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='sportscenter',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='sportscenterowner',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='contact',
        ),
        migrations.AddField(
            model_name='assignedpendingsportscenter',
            name='phone number',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coaches',
            name='phone number',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachmanagement',
            name='phone number',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportscenter',
            name='phone number',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportscenterowner',
            name='phone number',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='phone number',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
    ]
