# Generated by Django 4.0.3 on 2022-03-31 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_remove_assignedpendingsportscenter_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedpendingsportscenter',
            old_name='phone number',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='coaches',
            old_name='phone number',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='coachmanagement',
            old_name='phone number',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='sportscenter',
            old_name='phone number',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='sportscenterowner',
            old_name='phone number',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='usermanagement',
            old_name='phone number',
            new_name='contact',
        ),
    ]
