# Generated by Django 4.0.3 on 2022-03-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_alter_sportscenter_timings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('package', models.CharField(max_length=70)),
                ('packagebasevalue', models.CharField(max_length=40)),
                ('discountgiven', models.CharField(max_length=70)),
                ('paymentmode', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=60)),
            ],
        ),
    ]
