# Generated by Django 4.0.3 on 2022-04-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_dietplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='timings',
            field=models.CharField(blank=True, choices=[('05:00 AM to 06:00 PM', '05:00 AM to 06:00 PM')], default=1, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sportscenter',
            name='timings',
            field=models.CharField(blank=True, choices=[('05:00 AM-08:00 PM', '05:00 AM-08:00 PM')], default='05:00 AM to 08:00 PM', max_length=30, null=True),
        ),
    ]
