# Generated by Django 4.0.3 on 2022-04-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_rename_month_plan_subscription_one_month_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coaches',
            name='specialization',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachmanagement',
            name='email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachmanagement',
            name='specialization',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportscenter',
            name='email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportscenterowner',
            name='email',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportscenterowner',
            name='timings',
            field=models.CharField(blank=True, choices=[('05:00 AM-08:00 PM', '05:00 AM-08:00 PM')], default='05:00 AM to 08:00 PM', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
