# Generated by Django 4.0.3 on 2022-04-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_coaches_email_coaches_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_center_owner', models.IntegerField()),
                ('coach', models.IntegerField()),
                ('end_user', models.IntegerField()),
            ],
        ),
    ]
