# Generated by Django 4.0.3 on 2022-04-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_setting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='UploadPost',
        ),
    ]
