# Generated by Django 4.0.3 on 2022-04-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_rename_post_uploadpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportscenterowner',
            name='timings',
            field=models.CharField(blank=True, choices=[('05:00 AM-10:00 PM', '05:00 AM-10:00 PM')], default='05:00 AM to 10:00 PM', max_length=30, null=True),
        ),
    ]
