# Generated by Django 4.0.3 on 2022-04-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_alter_usermanagement_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
    ]
