# Generated by Django 4.0.3 on 2022-04-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_alter_usermanagement_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportscenter',
            name='timings',
        ),
        migrations.AddField(
            model_name='sportscenter',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportscenter',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
