# Generated by Django 4.0.3 on 2022-04-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_remove_sportscenter_timings_sportscenter_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportscenter',
            name='time_from',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sportscenter',
            name='time_to',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
