# Generated by Django 4.0.3 on 2022-04-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_alter_sportscenter_time_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanagement',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='last_name',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
