# Generated by Django 4.0.3 on 2022-04-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0048_rename_name_usermanagement_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanagement',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='last_name',
        ),
    ]
