# Generated by Django 4.0.3 on 2022-04-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0049_rename_first_name_usermanagement_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='sportscenter',
            new_name='sports_center',
        ),
        migrations.RenameField(
            model_name='coaches',
            old_name='sportscenter',
            new_name='sports_center',
        ),
        migrations.RenameField(
            model_name='coachmanagement',
            old_name='coachname',
            new_name='coach_name',
        ),
        migrations.RenameField(
            model_name='coachmanagement',
            old_name='sportscenter',
            new_name='sports_center',
        ),
        migrations.RenameField(
            model_name='dietplan',
            old_name='eveningsnacks',
            new_name='evening_snacks',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='sportscenter',
            new_name='sports_center',
        ),
        migrations.RenameField(
            model_name='sportscenterowner',
            old_name='ownername',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='sportscenterowner',
            old_name='sportscenter',
            new_name='sports_center',
        ),
        migrations.RenameField(
            model_name='subscriptionplans',
            old_name='sportscenter',
            new_name='sports_center',
        ),
        migrations.RenameField(
            model_name='transcationdetail',
            old_name='discountgiven',
            new_name='discount_given',
        ),
        migrations.RenameField(
            model_name='transcationdetail',
            old_name='packagebasevalue',
            new_name='package_base_value',
        ),
        migrations.RenameField(
            model_name='transcationdetail',
            old_name='paymentmode',
            new_name='payment_mode',
        ),
        migrations.RenameField(
            model_name='transcations',
            old_name='sportscenter',
            new_name='sports_center',
        ),
    ]
