# Generated by Django 4.0.3 on 2022-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0053_rename_second_name_usermanagement_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagement',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='name',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
