# Generated by Django 4.0.3 on 2022-04-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_remove_usermanagement_name_usermanagement_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachmanagement',
            name='specialization',
            field=models.CharField(choices=[('cardio', 'cardio'), ('strength', 'strength')], default='cardio', max_length=100),
        ),
    ]
