# Generated by Django 4.0.3 on 2022-04-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_alter_coachmanagement_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportscenterowner',
            name='timings',
            field=models.CharField(blank=True, choices=[('1', '05:00 AM-10:00 PM')], default='05:00 AM to 10:00 PM', max_length=30, null=True),
        ),
    ]
