# Generated by Django 4.0.3 on 2022-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0058_alter_coachmanagement_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachmanagement',
            name='specialization',
            field=models.CharField(choices=[('1', 'cardio'), ('2', 'strength')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='sportscenterowner',
            name='timings',
            field=models.CharField(blank=True, choices=[('1', '05:00 AM-10:00 PM')], default=1, max_length=30, null=True),
        ),
    ]
