# Generated by Django 4.0.3 on 2022-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0059_alter_coachmanagement_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='timings',
            field=models.CharField(blank=True, choices=[('1', '05:00 AM to 06:00 PM')], default='05:00 AM to 06:00 PM', max_length=40, null=True),
        ),
    ]
