# Generated by Django 4.0.3 on 2022-04-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0060_alter_schedule_timings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanagement',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='usermanagement',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='usermanagement',
            old_name='contact',
            new_name='phonenumber',
        ),
    ]
