# Generated by Django 4.0.3 on 2022-04-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0063_alter_usermanagement_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachmanagement',
            old_name='coach_name',
            new_name='coachname',
        ),
        migrations.RenameField(
            model_name='coachmanagement',
            old_name='sports_center',
            new_name='sportscenter',
        ),
    ]
