# Generated by Django 4.0.3 on 2022-04-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0064_rename_coach_name_coachmanagement_coachname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachmanagement',
            old_name='coachname',
            new_name='name',
        ),
    ]
