# Generated by Django 4.0.3 on 2022-04-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0066_rename_sportscenter_coachmanagement_sportcenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='sports_center',
            new_name='sportscenter',
        ),
    ]
