# Generated by Django 4.0.3 on 2022-04-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0068_rename_sportscenter_categories_sportcenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportscenterowner',
            old_name='owner_name',
            new_name='ownername',
        ),
        migrations.RenameField(
            model_name='sportscenterowner',
            old_name='contact',
            new_name='phoneno',
        ),
        migrations.RenameField(
            model_name='sportscenterowner',
            old_name='sports_center',
            new_name='sportcenter',
        ),
        migrations.RemoveField(
            model_name='sportscenterowner',
            name='timings',
        ),
        migrations.AddField(
            model_name='sportscenterowner',
            name='closetimings',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportscenterowner',
            name='opentimings',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
