# Generated by Django 4.0.3 on 2022-04-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0069_rename_owner_name_sportscenterowner_ownername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='end_user',
            new_name='enduser',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='sports_center_owner',
            new_name='sportscenterowner',
        ),
    ]
