# Generated by Django 4.0.3 on 2022-04-19 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0070_rename_end_user_setting_enduser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='sportscenterowner',
            new_name='sportcenterowner',
        ),
    ]
