# Generated by Django 4.0.3 on 2022-04-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0073_alter_categories_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
    ]
