# Generated by Django 4.0.3 on 2022-04-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0074_alter_usermanagement_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachmanagement',
            old_name='specialization',
            new_name='specialisation',
        ),
    ]
