# Generated by Django 4.0.3 on 2022-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0075_rename_specialization_coachmanagement_specialisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportscenterowner',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
