# Generated by Django 4.0.3 on 2022-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0076_sportscenterowner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportscenterowner',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
