# Generated by Django 4.0.3 on 2022-04-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0077_alter_sportscenterowner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportscenterowner',
            name='image',
        ),
    ]
