# Generated by Django 4.0.3 on 2022-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0078_remove_sportscenterowner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportscenterowner',
            name='document',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportscenterowner',
            name='logo',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
