# Generated by Django 4.0.3 on 2022-04-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0079_sportscenterowner_document_sportscenterowner_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportscenterowner',
            name='document',
        ),
        migrations.RemoveField(
            model_name='sportscenterowner',
            name='logo',
        ),
    ]
