# Generated by Django 4.0.3 on 2022-04-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0080_remove_sportscenterowner_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportscenter',
            old_name='time_from',
            new_name='timefrom',
        ),
        migrations.RenameField(
            model_name='sportscenter',
            old_name='time_to',
            new_name='timeto',
        ),
    ]
