# Generated by Django 4.0.3 on 2022-04-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0081_rename_time_from_sportscenter_timefrom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coaches',
            old_name='Contact',
            new_name='phoneno',
        ),
        migrations.RenameField(
            model_name='coaches',
            old_name='specialization',
            new_name='speciallsation',
        ),
        migrations.RenameField(
            model_name='coaches',
            old_name='sports_center',
            new_name='sportscenter',
        ),
    ]
