# Generated by Django 4.0.3 on 2022-04-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0084_alter_categories_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='sport',
            field=models.CharField(choices=[('tennis', 'Tennis'), ('football', 'Football'), ('boxing', 'Boxing'), ('wrestling', 'Wrestling'), ('weightlifting', 'Weightlifting'), ('gymnastics', 'Gymnastics'), ('squash', 'Squash'), ('shooting', 'Shooting'), ('badminton', 'Badminton')], max_length=60),
        ),
    ]
