# Generated by Django 4.0.3 on 2022-04-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0086_alter_transcationdetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
