# Generated by Django 4.0.3 on 2022-04-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0087_alter_transcations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportscenterowner',
            name='closetimings',
            field=models.CharField(choices=[('1AM', '01:00 AM'), ('2AM', '02:00 AM'), ('3AM', '03:00 AM'), ('4AM', '04:00 AM'), ('5AM', '05:00 AM'), ('6AM', '06:00 AM'), ('7AM', '07:00 AM'), ('8AM', '08:00 AM'), ('9AM', '09:00 AM'), ('10AM', '10:00 AM'), ('11AM', '11:00 AM'), ('12PM', '12:00 PM'), ('1PM', '01:00 PM'), ('2PM', '02:00 PM'), ('3PM', '03:00 PM'), ('4PM', '04:00 PM'), ('5PM', '05:00 PM'), ('6PM', '06:00 PM'), ('7PM', '07:00 PM'), ('8PM', '08:00 PM'), ('9PM', '09:00 PM'), ('10PM', '10:00 PM'), ('11PM', '11:00 PM'), ('12AM', '12:00 AM')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sportscenterowner',
            name='opentimings',
            field=models.CharField(choices=[('1AM', '01:00 AM'), ('2AM', '02:00 AM'), ('3AM', '03:00 AM'), ('4AM', '04:00 AM'), ('5AM', '05:00 AM'), ('6AM', '06:00 AM'), ('7AM', '07:00 AM'), ('8AM', '08:00 AM'), ('9AM', '09:00 AM'), ('10AM', '10:00 AM'), ('11AM', '11:00 AM'), ('12PM', '12:00 PM'), ('1PM', '01:00 PM'), ('2PM', '02:00 PM'), ('3PM', '03:00 PM'), ('4PM', '04:00 PM'), ('5PM', '05:00 PM'), ('6PM', '06:00 PM'), ('7PM', '07:00 PM'), ('8PM', '08:00 PM'), ('9PM', '09:00 PM'), ('10PM', '10:00 PM'), ('11PM', '11:00 PM'), ('12AM', '12:00 AM')], max_length=30),
        ),
    ]
