# Generated by Django 4.0.3 on 2022-04-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0089_alter_sportscenterowner_closetimings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSportCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=40)),
                ('phoneno', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], max_length=10)),
                ('timings', models.CharField(max_length=50)),
            ],
        ),
    ]
