# Generated by Django 4.0.3 on 2022-04-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0093_alter_sportscenterowner_closetimings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportscenterowner',
            name='closetimings',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sportscenterowner',
            name='opentimings',
            field=models.CharField(max_length=30),
        ),
    ]
