# Generated by Django 4.0.3 on 2022-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0094_alter_sportscenterowner_closetimings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCoaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('sport', models.CharField(max_length=100)),
                ('sportcenter', models.CharField(max_length=100)),
                ('timings', models.CharField(max_length=100)),
            ],
        ),
    ]
