# Generated by Django 4.0.3 on 2022-05-05 05:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0095_schedulecoaches'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Chat',
        ),
    ]
