# Generated by Django 4.0.3 on 2022-05-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0096_rename_message_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='sports_center',
            new_name='sportscenter',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='transcationdetail',
            old_name='discount_given',
            new_name='discountgiven',
        ),
        migrations.RenameField(
            model_name='transcationdetail',
            old_name='package_base_value',
            new_name='packagebasevalue',
        ),
        migrations.RenameField(
            model_name='transcationdetail',
            old_name='payment_mode',
            new_name='paymentmode',
        ),
        migrations.RenameField(
            model_name='transcations',
            old_name='sports_center',
            new_name='sportcenter',
        ),
        migrations.RenameField(
            model_name='transcations',
            old_name='user_name',
            new_name='username',
        ),
    ]
