# Generated by Django 4.0.3 on 2022-05-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0097_rename_sports_center_schedule_sportscenter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplans',
            old_name='sports_center',
            new_name='sportcenter',
        ),
    ]
