# Generated by Django 4.0.3 on 2022-05-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0099_rename_evening_snacks_dietplan_eveningsnacks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='sportscenter',
            new_name='sportcenter',
        ),
        migrations.RenameField(
            model_name='transcations',
            old_name='Date',
            new_name='date',
        ),
    ]
