# Generated by Django 4.0.3 on 2022-05-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0101_chatmessage_thread_delete_chat_chatmessage_thread_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='first',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
