# Generated by Django 3.2.8 on 2022-05-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0102_remove_thread_first_remove_thread_second_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedpendingsportscenter',
            old_name='name',
            new_name='centername',
        ),
        migrations.RenameField(
            model_name='assignedpendingsportscenter',
            old_name='contact',
            new_name='phoneno',
        ),
        migrations.AddField(
            model_name='assignedpendingsportscenter',
            name='price',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedpendingsportscenter',
            name='services',
            field=models.CharField(choices=[('strength', 'strength'), ('cardio', 'cardio')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
