# Generated by Django 4.0.3 on 2022-05-16 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0105_rename_subscription_usersubscription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DietPlan',
            new_name='UserDietPlan',
        ),
    ]
