# Generated by Django 4.0.3 on 2022-05-16 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0106_rename_dietplan_userdietplan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDietPlan',
            new_name='DietPlan',
        ),
        migrations.RenameModel(
            old_name='UserSubscription',
            new_name='Subscription',
        ),
        migrations.RenameModel(
            old_name='OwnerSubscriptionPlans',
            new_name='SubscriptionPlans',
        ),
    ]
