# Generated by Django 4.0.3 on 2022-05-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0107_rename_userdietplan_dietplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='timings',
            field=models.CharField(default=None, max_length=60),
            preserve_default=False,
        ),
    ]
