# Generated by Django 4.0.3 on 2022-05-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0108_alter_schedule_timings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadpost',
            old_name='video',
            new_name='uploadpost',
        ),
        migrations.RemoveField(
            model_name='uploadpost',
            name='image',
        ),
        migrations.AddField(
            model_name='uploadpost',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
