# Generated by Django 4.0.3 on 2022-05-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0109_rename_video_uploadpost_uploadpost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietPlan',
        ),
    ]
