# Generated by Django 4.0.3 on 2022-05-18 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0111_weekdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunch', models.CharField(max_length=100)),
                ('eveningsnacks', models.CharField(max_length=100)),
                ('dinner', models.CharField(max_length=100)),
                ('breakfast', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main_app.weekdays')),
            ],
        ),
    ]
