# Generated by Django 4.0.3 on 2022-05-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0113_alter_dietplan_breakfast_alter_weekdays_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='weekdays',
            field=models.ForeignKey(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=None, max_length=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.weekdays'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='days',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1),
        ),
    ]
