# Generated by Django 4.0.3 on 2022-05-18 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0114_dietplan_weekdays_alter_weekdays_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='weekdays',
            field=models.ForeignKey(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20, on_delete=django.db.models.deletion.CASCADE, to='main_app.weekdays'),
        ),
        migrations.AlterField(
            model_name='weekdays',
            name='days',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20),
        ),
    ]
