# Generated by Django 4.0.3 on 2022-05-18 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0115_alter_dietplan_weekdays_alter_weekdays_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='weekdays',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='main_app.weekdays'),
        ),
    ]
