# Generated by Django 4.0.3 on 2022-05-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0116_alter_dietplan_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='breakfast',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='dinner',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='eveningsnacks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='lunch',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='weekdays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.weekdays'),
        ),
    ]
