# Generated by Django 4.0.3 on 2022-05-19 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0117_alter_dietplan_breakfast_alter_dietplan_dinner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaches',
            name='sportscenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.sportscenter'),
        ),
    ]
