# Generated by Django 4.0.3 on 2022-05-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0119_remove_usermanagement_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagement',
            name='sports_center_owner',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='user',
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='email',
            field=models.EmailField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='location',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='phone_no',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
