# Generated by Django 4.0.3 on 2022-05-23 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0122_alter_usermanagement_sports_center_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='sports_center_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sports_center_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
