# Generated by Django 4.0.3 on 2022-05-26 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0123_alter_usermanagement_sports_center_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachmanagement',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='coachmanagement',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coachmanagement',
            name='location',
        ),
        migrations.RemoveField(
            model_name='coachmanagement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coachmanagement',
            name='specialisation',
        ),
        migrations.RemoveField(
            model_name='coachmanagement',
            name='sportcenter',
        ),
        migrations.AddField(
            model_name='coachmanagement',
            name='coach_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachmanagement',
            name='owner_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
