# Generated by Django 4.0.3 on 2022-05-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0124_remove_coachmanagement_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportscenter',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.sportscenterowner'),
        ),
    ]
