# Generated by Django 4.0.3 on 2022-05-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0125_sportscenter_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportscenter',
            name='owner',
        ),
    ]
