# Generated by Django 4.0.3 on 2022-05-26 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0126_remove_sportscenter_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportscenter',
            name='sports_center_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.sportscenterowner'),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='coaches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.coaches'),
        ),
    ]
