# Generated by Django 4.0.3 on 2022-05-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0127_sportscenter_sports_center_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coaches',
            old_name='sportscenter',
            new_name='sports_center',
        ),
        migrations.RemoveField(
            model_name='sportscenter',
            name='sports_center_owner',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='coaches',
        ),
    ]
